/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package importador;


import com.csvreader.CsvReader;
//import com.sun.xml.internal.ws.policy.privateutil.PolicyUtils;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
//import java.util.List;
import java.util.Properties;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author adrians
 */
public class ventana_principal extends javax.swing.JFrame {
    
    AOrigen archivos = new AOrigen();
    Calendar fecha = Calendar.getInstance();
    int anio = fecha.get(Calendar.YEAR);
    int mes = fecha.get(Calendar.MONTH) + 1;
    int dia = fecha.get(Calendar.DAY_OF_MONTH);
    ArrayList<Productos> productos = new ArrayList<Productos>();
    ArrayList<Clientes> clientes = new ArrayList<Clientes>();
    ArrayList<Vendedores> vendedores = new ArrayList<Vendedores>();
    
    String[] listaProductosSeleccionados=new String[10000];
    
    /**
     * Creates new form ventana_principal
     */
    public ventana_principal() {
        initComponents();
        get_inicio_propiedades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jButton4.setText("importar ahora");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("origen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("destino");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("seleccione");

        jLabel3.setText("seleccione");

        jButton6.setText("importar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jButton6))
                        .addGap(0, 715, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String texto= abrirBuscadorArchivo();
        set_properties("origen", texto);
        jLabel2.setText(texto);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String texto= abrirBuscadorArchivo();
       set_properties("destino", texto);
       jLabel3.setText(texto);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        
        Properties prop = new Properties();
        InputStream is = null;
        try {
            is = new FileInputStream("C:/Users/adrians/Desktop/archivos_convertidos/config.properties");
            prop.load(is);
            
            String sDirectorOrigen = prop.getProperty("origen");
            String sDirectorDestino = prop.getProperty("destino");
            
            File origen = new File(sDirectorOrigen);
            File destino = new File(sDirectorDestino);
            
            if (origen.exists()){
                jTextArea1.append("existe el directorio origen");
                if (destino.exists()){
                    jTextArea1.append("\n existe el directorio destino");
                    if (verificar_origen(origen)){
                        jTextArea1.append("\n nombre: "+archivos.getNombre_archivo_MASNTHG());
                        jTextArea1.append("\n ruta: "+archivos.getRuta_archivo_MASNTHG());
                        jTextArea1.append("\n nombre: "+archivos.getNombre_archivo_MASNTHG_CLIENTES());
                        jTextArea1.append("\n ruta: "+archivos.getRuta_archivo_MASNTHG_CLIENTES());
                        jTextArea1.append("\n nombre: "+archivos.getNombre_archivo_MASNTHG_MAEART());
                        jTextArea1.append("\n ruta: "+archivos.getRuta_archivo_MASNTHG_MAEART());
                        jTextArea1.append("\n nombre: "+archivos.getNombre_archivo_MASNTHG_MSTOCK());
                        jTextArea1.append("\n ruta: "+archivos.getRuta_archivo_MASNTHG_MSTOCK());
                        jTextArea1.append("\n nombre: "+archivos.getNombre_archivo_MASNTHG_MVTA());
                        jTextArea1.append("\n ruta: "+archivos.getRuta_archivo_MASNTHG_MVTA());
                        
                        //generar CADPROD---------------------------------------------------------------------------------------------------------------
                        
                        String ficheroCadProd=generar_ruta_archivo(sDirectorDestino, "ACC_CADPROD");
                        jTextArea1.append("\n fichero creado: "+ficheroCadProd);
                        File archivoCadProd = new File(ficheroCadProd);
                        BufferedWriter cadProd;

                        String cod_cliente_cod_prod="30710665466";
                        String fecha_cod_prod=obtenerFechaFormateada();
                        cadProd = new BufferedWriter(new FileWriter(archivoCadProd));

                        cadProd.write("H;"+cod_cliente_cod_prod+";"+fecha_cod_prod+";"+fecha_cod_prod);

                        cadProd.newLine();

                        try {
                            //con el siguiente codigo se recorre los articulos para poder generar el cadprod
                            CsvReader csvReaderCodArt = new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_MAEART()));
                            csvReaderCodArt.readHeaders();
                            //con la linea siguiente cargo los productos de unilever en un arreglo para consultar en otros archivos
                            CsvReader csvReaderCodAllArt = new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_MAEART()));
                            csvReaderCodAllArt.readHeaders();
                            generar_productos(csvReaderCodAllArt);
                            //con las siguientes lineas cargo los datos del cliente en un arreglo de objetos de tipo cliente.
                            CsvReader csvReaderClientes= new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_CLIENTES()));
                            csvReaderClientes.readHeaders();
                            generar_clientes(csvReaderClientes);
                            //con las siguientes lineas cargo los datos de los vendedores
                            CsvReader csvReaderVendedores= new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_VENDEDOR()));
                            csvReaderVendedores.readHeaders();
                            generar_vendedores(csvReaderVendedores);
                            
                            while (csvReaderCodArt.readRecord()) {
                                if(true){
                                    if(csvReaderCodArt.get(8).equals("00104")){
                                        generarLineaCadProd(csvReaderCodArt, cadProd);
                                    }
                                }else{
                                    generarLineaCadProd(csvReaderCodArt, cadProd);
                                }   
                            }
                            csvReaderCodArt.close();
                        } catch (FileNotFoundException ex) {
//                            Logger.getLogger(Importador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        cadProd.write("E");

                        cadProd.close();
                        
                         //generar CADSITE---------------------------------------------------------------------------------------------------------------
                        String ficheroCadSite=generar_ruta_archivo(sDirectorDestino, "ACC_CADSITE");
                        jTextArea1.append("\n fichero creado: "+ficheroCadSite);
                        File archivoCadSite = new File(ficheroCadSite);
                        BufferedWriter cadSite;

                        String cod_cliente_cod_site="30710665466";
                        String fecha_cod_site=obtenerFechaFormateada();
                        cadSite = new BufferedWriter(new FileWriter(archivoCadSite));

                        cadSite.write("H;"+cod_cliente_cod_site+";"+fecha_cod_site);

                        cadSite.newLine();
                        
                        boolean tienda_uno=true;
                        
                        if(tienda_uno){
                            String cod_tienda1 ="30710665466";
                            String desc_tienda1="masabores";
                            String estado_tienda1="HG";
                            String ciudad_tienda1="cordoba";
                            String barrio_tienda1="punilla";
                            String codigo_postal_tienda1="5174";
                            String estado_tienda_1="CD";

                            cadSite.write("V;"+cod_tienda1+";"+desc_tienda1+";"+estado_tienda1+";"+ciudad_tienda1+";"+barrio_tienda1+";"+codigo_postal_tienda1+";"+estado_tienda_1);

                            cadSite.newLine();
                        }
                        
                        boolean tienda_dos=true;
                        
                        if(tienda_dos){
                            String cod_tienda2 ="30710665466";
                            String desc_tienda2="masabores";
                            String estado_tienda2="LF";
                            String ciudad_tienda2="cordoba";
                            String barrio_tienda2="punilla";
                            String codigo_postal_tienda2="5172";
                            String estado_tienda_2="CD";

                            cadSite.write("V;"+cod_tienda2+";"+desc_tienda2+";"+estado_tienda2+";"+ciudad_tienda2+";"+barrio_tienda2+";"+codigo_postal_tienda2+";"+estado_tienda_2);

                            cadSite.newLine();
                        }

                        cadSite.write("E");

                        cadSite.close();
                        
                        
                        //generar SELLOUT-----------------------------------------------------------------------------------------------------------
                        String fichero=generar_ruta_archivo(sDirectorDestino, "ACC_SELLOUT");
                        jTextArea1.append("\n fichero creado: "+fichero);
                        File archivo = new File(fichero);
                        BufferedWriter bw;

                        String cod_cliente="30710665466";
                        String fecha=obtenerFechaFormateada();
                        bw = new BufferedWriter(new FileWriter(archivo));

                        

                        try {
                            
                            String linea_cabecera="H;"+cod_cliente+";"+generarCabeceraSellOut();
                            
                            bw.write(linea_cabecera);

                            bw.newLine();
                            CsvReader csvReader = new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_MSTOCK()));
                            csvReader.readHeaders();

                            while (csvReader.readRecord()) {
                                
                                
                                if(estaEnArrayProductosSeleccionados(csvReader.get(12))){
                                    if(csvReader.get(8).equals("1")){
                                        if(csvReader.get(7).equals("01") || csvReader.get(7).equals("02") || csvReader.get(7).equals("12")){
                                                                                    
     //                                String codCd="99999999999999";
     //                                String codFab="77775423697546";
     //                                String codBarra="7896543216668";
    //                                String cantidad="1000";
    //                                String valorLiquido="12000";
    //                                String moneda="BRL";
    //                                String identificadorTrans="1535285";
    //                                String fechaTras="20150119";
    //                                String tipoDeTrans="V";
    //                                String tipoIdenfPDV="1";
    //                                String identificadorPDV="44148564985645";
    //                                String descripPDV="CLIENTE XYZ";
    //                                String codPostPDV="95687412";
    //                                String clasifPDV="OTROS";
    //                                String vendedor="2 - MARCIO SILVA";
                                            String codCd="30710665466";
                                            String codFab="30501092696";
                                            String codBarra=csvReader.get(51);
                                            String cantidad=generarVolEmbalaje(csvReader.get(14));
                                            String valorLiquido=generarValorLiquido(csvReader.get(14), csvReader.get(17));
                                            String moneda="ARS";
                                            
                                            String selectoIdentificador=csvReader.get(3)+csvReader.get(4)+csvReader.get(5);
                                            
                                            String identificadorTrans=selectoIdentificador;
                                            String fechaTras=generarFechaRegistro(csvReader.get(0));
                                            String tipoDeTrans=tipoTransaccion(csvReader.get(7));
                                            
                                            String tipoIdenfPDV="1";
                                            String identificadorPDV=obtener_cuil_cliente(csvReader.get(1));
                                            String descripPDV=csvReader.get(2);
                                            String codPostPDV=obtener_cod_postal(csvReader.get(1));
                                            String clasifPDV="OTROS";
                                            String vendedor=obtener_vendedor(csvReader.get(9));

                                            bw.write("V;"+codCd+";"+codFab+";"+codBarra+";"+cantidad+";"+valorLiquido+";"+moneda+";"+identificadorTrans+";"+fechaTras+";"+tipoDeTrans+";"+tipoIdenfPDV+";"+identificadorPDV+";"+descripPDV+";"+codPostPDV+";"+clasifPDV+";"+vendedor);

                                            bw.newLine(); 
                                        }
                                    }
                                }
                            }
                            csvReader.close();
                        } catch (FileNotFoundException ex) {
//                            Logger.getLogger(Importador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        bw.write("E");
                        bw.close();
                        //POSESTQ--------------------------------------------------------------------------------------------------------
                       
                            String ficheroPosestq=generar_ruta_archivo(sDirectorDestino, "ACC_POSESTQ");
                            jTextArea1.append("\n fichero creado: "+ficheroPosestq);
                            File archivoPosestq= new File(ficheroPosestq);
                            BufferedWriter posetoc=new BufferedWriter(new FileWriter(archivoPosestq));
                        
                        try {
                            String cod_cliente_pose="30710665466";
                            String fecha_pose=obtenerFechaFormateada();
                            
                            posetoc.write("H;"+cod_cliente_pose+";"+fecha_pose+";"+fecha_pose);

                            posetoc.newLine();
                        
                        
                            //con el siguiente codigo se recorre los articulos para poder generar el pose
                            CsvReader csvReaderCodArtPose = new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_MAEART()));
                            csvReaderCodArtPose.readHeaders();
                                while (csvReaderCodArtPose.readRecord()) {
                                if(true){
                                    if(csvReaderCodArtPose.get(8).equals("00104")){
                                        generarLineaPose(csvReaderCodArtPose, posetoc);
                                    }
                                }else{
                                    generarLineaPose(csvReaderCodArtPose, posetoc);
                                }   
                            }
                            csvReaderCodArtPose.close();
                        } catch (FileNotFoundException ex) {
//                            Logger.getLogger(Importador.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        posetoc.write("E");

                        posetoc.close();
                        
                        //generar PDV---------------------------------------------------------------------------------------------------------------
                        String ficheroPdv=generar_ruta_archivo(sDirectorDestino, "ACC_PDVS");
                        jTextArea1.append("\n fichero creado: "+ficheroPdv);
                        File archivoPdv = new File(ficheroPdv);
                        BufferedWriter pdv;

                        String cod_cliente_pdv="30710665466";
                        String fecha_pdv=obtenerFechaFormateada();
                        pdv = new BufferedWriter(new FileWriter(archivoPdv));

                        pdv.write("H;"+cod_cliente_pdv+";"+fecha_pdv);

                        pdv.newLine();
                        try{
                            //con el siguiente codigo se recorre los articulos para poder generar el pdv
                            CsvReader csvReaderPdv = new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_CLIENTES()));
                            csvReaderPdv.readHeaders();
                            while (csvReaderPdv.readRecord()) {
                                String cod_tributaria =csvReaderPdv.get(10);
                                String cod_tributariaRemplazadoGuion=cod_tributaria.replace("-", "");
//                                String cod_tributariaRemplazadoEspacios=cod_tributariaRemplazadoGuion.replaceAll("\\s","");
                                if(!sonEspacios(cod_tributariaRemplazadoGuion)){
                                    String razon_social=csvReaderPdv.get(2);
                                    String nom_comercial=csvReaderPdv.get(17);
                                    String pais_pdv="AR"; 
                                    String region_pdv="S";
                                    String estado_pdv=generarEstado(csvReaderPdv.get(5));
                                    String ciudad_pdv=csvReaderPdv.get(4);
                                    String barrio_pdv="BARRIO";
                                    String direccion_pdv=csvReaderPdv.get(3);
                                    String grupo_pdv="GRUPO ABC";
                                    String clasificacion_pdv="OTROS";
                                    String vededo_pdv=obtener_vendedor(csvReaderPdv.get(68));
                                    String fechareg_pdv=generarFechaRegistro(csvReaderPdv.get(61));
                                    String cod_pos_pdv=csvReaderPdv.get(6);
                                    String contacto_pdv=csvReaderPdv.get(8);
                                    String estatus_pdv=generarClienteActivoInactivo(csvReaderPdv.get(46));

                                    pdv.write("V;"+cod_tributariaRemplazadoGuion+";"+razon_social+";"+nom_comercial+";"+pais_pdv+";"+region_pdv+";"+estado_pdv+";"+ciudad_pdv+";"+barrio_pdv+";"+direccion_pdv+";"+grupo_pdv+";"+clasificacion_pdv+";"+vededo_pdv+";"+fechareg_pdv+";"+cod_pos_pdv+";"+contacto_pdv+";"+estatus_pdv);

                                    pdv.newLine();
                                }    
                                
                                
                        
                            }
                            csvReaderPdv.close();
                            } catch (FileNotFoundException ex) {
//                            Logger.getLogger(Importador.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        pdv.write("E");

                        pdv.close();
                        
                    }
                }else {  
                    jTextArea1.append("\n no existe el directorio destino");
                }
            }else {  
                jTextArea1.append("\n no existe el directorio origen");
            }
            
             
        } catch(IOException e) {
                System.out.println(e.toString());
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public String generarClienteActivoInactivo(String campo){
        String campoActivo="A";
        if(campo.equals("S")){
            campoActivo="I";
        }
        return campoActivo;
    }
    
    public String generarEstado(String cod_estado){
        String estado="CB";
        int cod_estado_ingresado=Integer.valueOf(cod_estado);
        if(!sonEspacios(cod_estado)){
            switch(cod_estado_ingresado){
                case 0:
                    estado="CB";
                break;
                case 1:
                    estado="CF";
                break; 
                case 2:
                    estado="CF";
                break;
                case 3:
                    estado="CB";
                break;
                case 4:
                    estado="CB";
                break;
                case 5:
                    estado="CF";
                break;
                case 6:
                    estado="SJ";
                break;
                case 7:
                    estado="CB";
                break;
                case 8:
                    estado="TC";
                break;
                case 9:
                    estado="SF";
                break;
                case 10:
                    estado="CC";
                break;
                case 12:
                    estado="BS";
                break;
                case 13:
                    estado="MZ";
                break;
                case 14:
                    estado="MS";
                break;
                case 15:
                    estado="SL";
                break;
                case 19:
                    estado="SL";
                break;
                case 21:
                    estado="SF";
                break;
                default:
                    estado="CB";
                break;    
            }
        }
        return estado;
    }
    
    public boolean estaEnArrayProductosSeleccionados(String numero){
        return Arrays.asList(listaProductosSeleccionados).contains(numero);
    }
    
    public boolean sonEspacios(String cad){
        for(int i =0; i<cad.length(); i++)
            if(cad.charAt(i) != ' ')
                return false;

        return true;
    }
    
    private void mostrarArchivosFichero(File origen){
        File[] ficheros = origen.listFiles();
        for (int x=0;x<ficheros.length;x++){
           jTextArea1.append("\n"+ficheros[x].getName());
        }
    }
    
    private String tipoTransaccion(String tipo){
        String dato = "V";
        if(tipo.equals("02")){
            dato="DV";
        }
        if(tipo.equals("12")){
            dato="B";
        }
        return dato;        
    }
    
    private String obtenerFechaFormateada(){
        
        String mesFormateado=String.valueOf(mes);
        String diaFormateado=String.valueOf(dia);
        String anioFormateado=String.valueOf(anio);

        if(mes<10){
            mesFormateado="0"+mes;
        }
        
        if(dia<10){
            diaFormateado="0"+dia;
        }
        return anioFormateado+mesFormateado+diaFormateado;
    }
    
    private String generar_ruta_archivo(String directorio, String nombre){
        
        String ruta=directorio+"\\"+nombre+"_"+obtenerFechaFormateada()+".txt";
        return ruta;
    }
    
    private Boolean verificar_origen(File origen){
        boolean validacion=false;
        
        int clientes=0;
        int articulos=0;
        int stock=0;
        int venta=0;
        int ini=0;
        int vendedor=0;
        
        File[] ficheros = origen.listFiles();
        for (int x=0;x<ficheros.length;x++){
            String cadena = ficheros[x].getName();
            
            int resultadoCliente = cadena.indexOf("MASNTHG_CLIENTES.csv");
            int resultadoArticulos = cadena.indexOf("MASNTHG_MAEART.csv");
            int resultadoStock = cadena.indexOf("MASNTHG_MSTOCK.csv");
            int resultadoVenta = cadena.indexOf("MASNTHG_MVTA.csv");
            int resultadoVendedor = cadena.indexOf("MASNTHG_VENDEDOR.csv");
            int resultadoini = cadena.indexOf("MASNTHG.ini");

            if(resultadoCliente != -1) {
                clientes++;
                archivos.setNombre_archivo_MASNTHG_CLIENTES(cadena);
                archivos.setRuta_archivo_MASNTHG_CLIENTES(ficheros[x].getAbsolutePath());
            }
            if(resultadoArticulos != -1) {
                articulos++;
                archivos.setNombre_archivo_MASNTHG_MAEART(cadena);
                archivos.setRuta_archivo_MASNTHG_MAEART(ficheros[x].getAbsolutePath());
            }
            if(resultadoStock != -1) {
                stock++;
                archivos.setNombre_archivo_MASNTHG_MSTOCK(cadena);
                archivos.setRuta_archivo_MASNTHG_MSTOCK(ficheros[x].getAbsolutePath());
            }
            if(resultadoVenta != -1) {
                venta++;
                archivos.setNombre_archivo_MASNTHG_MVTA(cadena);
                archivos.setRuta_archivo_MASNTHG_MVTA(ficheros[x].getAbsolutePath());
            }
            if(resultadoini != -1) {
                ini++;
                archivos.setNombre_archivo_MASNTHG(cadena);
                archivos.setRuta_archivo_MASNTHG(ficheros[x].getAbsolutePath());
            }
            if(resultadoVendedor != -1) {
                vendedor++;
                archivos.setNombre_archivo_MASNTHG_VENDEDOR(cadena);
                archivos.setRuta_archivo_MASNTHG_VENDEDOR(ficheros[x].getAbsolutePath());
            }
        }
        validarCantidad(clientes, "MASNTHG_CLIENTES");
        validarCantidad(articulos, "MASNTHG_MAEART");
        validarCantidad(stock, "MASNTHG_MSTOCK");
        validarCantidad(venta, "MASNTHG_MVTA");
        validarCantidad(ini, "MASNTHG");
        validarCantidad(vendedor, "MASNTHG_VENDEDOR");
        
        if(clientes==1 && articulos==1 && stock ==1 && venta==1 && ini==1 && vendedor==1){
            validacion=true;
        }else{
             jTextArea1.append("\n archivos duplicados verifique los archivos en la carpeta origen");
        }
        
        return validacion;
    }
    
    private void generarLineaCadProd (CsvReader csvReaderCodArt, BufferedWriter cadProd) throws IOException{

        String codFab="30501092696";
        String descFab="UNILEVER DE ARGENTINA S.A.";
        String codProd=csvReaderCodArt.get(1);
        String descProd=csvReaderCodArt.get(2);
        String codGrup=csvReaderCodArt.get(6);
        String descGroup=csvReaderCodArt.get(7);
        String codFam="";
        String descFam="";
        String codSubFam="";
        String descSubFam="";
        String codBarra=csvReaderCodArt.get(3);
        String tipoEmbalaje=csvReaderCodArt.get(39);
        String volEmbalaje=generarVolEmbalaje(csvReaderCodArt.get(38));
        String estatusProd="A";
        String fechaRegistro=generarFechaRegistro(csvReaderCodArt.get(54));
        cadProd.write("V;"+codFab+";"+descFab+";"+codProd+";"+descProd+";"+codGrup+";"+descGroup+";"+codFam+";"+descFam+";"+codSubFam+";"+descSubFam+";E;"+codBarra+";"+tipoEmbalaje+";UN;"+volEmbalaje+";"+estatusProd+";"+fechaRegistro);
        cadProd.newLine(); 
    }
    
    private void generarLineaPose(CsvReader csvReaderCodArt, BufferedWriter pose) throws IOException{

        String codCliente="30710665466";
        String codBarras=csvReaderCodArt.get(3);
        String stock="0";
        String fecha=obtenerFechaFormateada();
        
        pose.write("V;"+codCliente+";"+codBarras+";"+stock+";H;"+fecha);
        pose.newLine(); 
    }
    
    private String generarCabeceraSellOut() throws IOException{
        String fecha="";
        ArrayList fechas=new ArrayList();
        String fecha_desde="";
        String fecha_hasta="";
        try {
                CsvReader csvReader = new CsvReader(new FileReader(archivos.getRuta_archivo_MASNTHG_MSTOCK()));
                csvReader.readHeaders();

                while (csvReader.readRecord()) {
                    if(estaEnArrayProductosSeleccionados(csvReader.get(12))){
                        if(csvReader.get(8).equals("1")){
                            if(csvReader.get(7).equals("01") || csvReader.get(7).equals("02") || csvReader.get(7).equals("12")){
                                int fechaSeleccionada=Integer.valueOf(generarFechaRegistro(csvReader.get(0)));
                                fechas.add(fechaSeleccionada);
                                
                                
                            }
                        }
                    }
                }
                Comparator<Integer> comparador = Collections.reverseOrder();
                Collections.sort(fechas, comparador);
                fecha_desde = String.valueOf(fechas.get(fechas.size() -1));
                fecha_hasta = String.valueOf(fechas.get(0));
                csvReader.close();
            } catch (FileNotFoundException ex) {
//                Logger.getLogger(Importador.class.getName()).log(Level.SEVERE, null, ex);
            }
            fecha=fecha_desde+";"+fecha_hasta;
            return fecha;
        }
    
    private void generar_productos(CsvReader  csvReaderCodArt) throws IOException{
        int indice=0;
        while (csvReaderCodArt.readRecord()) {
              if(csvReaderCodArt.get(8).equals("00104")){
//                  Productos p = new Productos();
//                  p.setCodigo_producto(csvReaderCodArt.get(1));
//                  p.setCodigo_proveedor("00104");
//                  p.setDescripcion_producto(csvReaderCodArt.get(2));
//                  productos.add(p);
                  listaProductosSeleccionados[indice]=csvReaderCodArt.get(1);
                  indice++;
              }
        }
    }
    
    private void generar_clientes(CsvReader  csvReaderClientes) throws IOException{
        
        while (csvReaderClientes.readRecord()) {
            Clientes c = new Clientes();
            c.setCodigo(csvReaderClientes.get(1));
            c.setCuil(csvReaderClientes.get(10));
            c.setApellido(csvReaderClientes.get(17));
            c.setRazon_social(csvReaderClientes.get(2));
            c.setCodigo_postal(csvReaderClientes.get(6));
            clientes.add(c);
        }
    }
    
    private void generar_vendedores(CsvReader  csvReaderVendedores) throws IOException{
        while (csvReaderVendedores.readRecord()) {  
            Vendedores v = new Vendedores();
            v.setCodigo(csvReaderVendedores.get(0));
            v.setNombre(csvReaderVendedores.get(1));
            vendedores.add(v);
        }
    }
        
    private String obtener_cod_postal(String cod_cliente_masabores){
        String codigoPostal = "99999999";
        for (int i = 0; i < clientes.size(); i++) {
            Clientes c= clientes.get(i);
            if(c.getCodigo().equals(cod_cliente_masabores)){
                if(c.getCodigo_postal()!=""){ 
                    codigoPostal=c.getCodigo_postal();
                }
               
            }
        }
        return codigoPostal;
    }
    
    private String obtener_cuil_cliente(String cod_cliente_masabores){
        String cuil = "00000000000000";
        for (int i = 0; i < clientes.size(); i++) {
            Clientes c= clientes.get(i);
            if(c.getCodigo().equals(cod_cliente_masabores)){
                cuil=c.getCuil();
            }
        }
                
        String remplazado=cuil.replace("-", "");
        
        return remplazado;
    }
    
    private String obtener_vendedor(String cod_vendedor_masabores){
        String vendedor = "0 - VENDEDOR";
        for (int i = 0; i < vendedores.size(); i++) {
            Vendedores v= vendedores.get(i);
            if(v.getCodigo().equals(cod_vendedor_masabores)){
                vendedor=v.getCodigo()+" - "+v.getNombre();
            }
        }
        return vendedor;
    }
    
    private boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    private boolean isFloat(String cadena){
	try {
		Float.parseFloat(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    private String generarVolEmbalaje(String cant){
        int cantidad = 0;
        if(isNumeric(cant)){
             cantidad = Integer.valueOf(cant);
             cantidad=cantidad*1000;
        }
        return String.valueOf(cantidad);
        
    }
    
    private String generarValorLiquido(String cant, String pre){
        int cantidad = 0;
        float precio = 0;
        float total = 0;
        float total_formatedo=0;
        
        if(isNumeric(cant)){
            if(isFloat(pre)){
                cantidad = Integer.valueOf(cant);
                precio = Float.valueOf(pre);
                total=cantidad*precio;
//                total_formatedo = Math.round(total * 100.0) / 100.0;
                total_formatedo=round(total, 2);
            }
             
        }
        
        total_formatedo = total_formatedo*100;
        int total_convertido = (int)total_formatedo;
        return String.valueOf(total_convertido);
        
    }
    
    public float round(float d, int decimalPlace) {
        BigDecimal bd = new BigDecimal(Float.toString(d));
        bd = bd.setScale(decimalPlace, BigDecimal.ROUND_HALF_UP);
        return bd.floatValue();
    }
    
    private String generarFechaRegistro(String dias){
        String fechaSeleccionada="";
        int diasSumados=Integer.valueOf(dias);
        Calendar cal = Calendar.getInstance();
        cal.set(1800,10,10,7,0,0);
        cal.add(Calendar.DAY_OF_MONTH, diasSumados); 
        
        int anio_selected = cal.get(Calendar.YEAR);
        int mes_selected = cal.get(Calendar.MONTH) + 1;
        int dia_selected = cal.get(Calendar.DAY_OF_MONTH);
        
        String mesFormateado=String.valueOf(mes_selected);
        String diaFormateado=String.valueOf(dia_selected);
        String anioFormateado=String.valueOf(anio_selected);
        
        if(mes_selected<10){
            mesFormateado="0"+mes_selected;
        }
        
        if(dia_selected<10){
            diaFormateado="0"+dia_selected;
        }
        
        
        fechaSeleccionada=anioFormateado+mesFormateado+diaFormateado;
        
        return fechaSeleccionada;
    }
    
    private void validarCantidad (int cantidad, String archivo){
        if(cantidad==1){
            jTextArea1.append("\n archivo "+archivo+" OK");
        }else{
            jTextArea1.append("\n archivo "+archivo+" no encontrado o duplicado");
        }
    }
    
    private String abrirBuscadorArchivo(){
        File abre;

        try
        {
            JFileChooser file = new JFileChooser();
            file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            file.showOpenDialog(this);

            abre = file.getSelectedFile();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "No se ha podido leer el archivo");
            abre = new File("");
        }

        return abre.getAbsolutePath();
    }
    
    private void set_properties(String propiedad, String valor){
        Properties prop = new Properties();
        InputStream is = null;
        try {
            is = new FileInputStream("C:/Users/adrians/Desktop/archivos_convertidos/config.properties");
            prop.load(is);
            prop.setProperty(propiedad, valor);

            prop.store(new FileWriter("C:/Users/adrians/Desktop/archivos_convertidos/config.properties"),"ultima actualizacion");
        } catch(IOException e) {
                System.out.println(e.toString());
        }
    }
    
    private void get_inicio_propiedades(){
        Properties prop = new Properties();
        InputStream is = null;
        try {
            is = new FileInputStream("C:/Users/adrians/Desktop/archivos_convertidos/config.properties");
            prop.load(is);
             jLabel2.setText(prop.getProperty("origen"));
             jLabel3.setText(prop.getProperty("destino"));
        } catch(IOException e) {
                System.out.println(e.toString());
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
    
}
